### Solicitar pedidos
GET http://localhost:5000/api/pedidos/

### Solicitar pedidos por ID
GET http://localhost:5000/api/pedidos/612d2bd8b523080b6f849438

### Solicitar pedidos por ID de usuario
GET http://localhost:5000/api/pedidos/usuarios/612d1fa4eff4fb054bd12be3

### Crear un pedido
POST http://localhost:5000/api/pedidos/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer (token)

{
    "id_usuario": "612f93aa6a88d598f9575ce2",
    "id_pizzas": ["612d6ba0f12ccdf1d2fc8e91"],
    "precio": 19.85
}

### Eliminar pedido por ID
DELETE http://localhost:5000/api/pedidos/612e534bf712736af860402b

### Modificar pedido
PATCH http://localhost:5000/api/pedidos/612d2bd8b523080b6f849438 HTTP/1.1
Content-Type: application/json

{
    "entregado": true
}